"""project documents

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 05:40:39.133746
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_documents_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_documents_project_id'))

    op.drop_table('project_documents')
    # ### end Alembic commands ###
